// Japanese insect names and meta — maps to keys in INSECT_SVG
window.BUG_META = {
  kabuto:   { jp: 'カブトムシ', en: 'Beetle', rarity: 5, habitat: 'クヌギ林' },
  miyama:   { jp: 'ミヤマクワガタ', en: 'Stag Beetle', rarity: 5, habitat: '山の雑木林' },
  okuw:     { jp: 'オオクワガタ', en: 'Giant Stag', rarity: 5, habitat: '樹洞' },
  herc:     { jp: 'ヘラクレスオオカブト', en: 'Hercules', rarity: 6, habitat: '熱帯雨林' },
  atlas:    { jp: 'アトラスオオカブト', en: 'Atlas Beetle', rarity: 5, habitat: '熱帯' },
  actaeon:  { jp: 'アクタエオンゾウカブト', en: 'Actaeon', rarity: 6, habitat: '南米' },
  ageha:    { jp: 'アゲハチョウ', en: 'Swallowtail', rarity: 3, habitat: '花畑' },
  morpho:   { jp: 'モルフォチョウ', en: 'Morpho', rarity: 5, habitat: '熱帯雨林' },
  lady:     { jp: 'テントウムシ', en: 'Ladybug', rarity: 1, habitat: '草むら' },
  bee:      { jp: 'ミツバチ', en: 'Honey Bee', rarity: 2, habitat: '花畑' },
  dragonfly:{ jp: 'トンボ', en: 'Dragonfly', rarity: 2, habitat: '池のそば' },
  cicada:   { jp: 'セミ', en: 'Cicada', rarity: 2, habitat: '木の幹' },
  firefly:  { jp: 'ホタル', en: 'Firefly', rarity: 4, habitat: '川べり' },
  batta:    { jp: 'バッタ', en: 'Grasshopper', rarity: 1, habitat: '草むら' },
  mantis:   { jp: 'カマキリ', en: 'Mantis', rarity: 3, habitat: '草むら' },
  ant:      { jp: 'アリ', en: 'Ant', rarity: 1, habitat: 'どこでも' },
  dango:    { jp: 'ダンゴムシ', en: 'Pillbug', rarity: 1, habitat: '落ち葉の下' },
  kok:      { jp: 'コオロギ', en: 'Cricket', rarity: 2, habitat: '草むら' },
  cricket:  { jp: 'スズムシ', en: 'Bell Cricket', rarity: 3, habitat: '草むら' },
  spider:   { jp: 'クモ', en: 'Spider', rarity: 2, habitat: '軒下' },
  snail:    { jp: 'カタツムリ', en: 'Snail', rarity: 2, habitat: '葉っぱ' },
  worm:     { jp: 'ミミズ', en: 'Worm', rarity: 1, habitat: '土の中' },
  moth:     { jp: 'ガ', en: 'Moth', rarity: 2, habitat: '夜の灯り' },
  fly:      { jp: 'ハエ', en: 'Fly', rarity: 1, habitat: 'どこでも' },
  inago:    { jp: 'イナゴ', en: 'Locust', rarity: 2, habitat: '田んぼ' },
  mayfly:   { jp: 'カゲロウ', en: 'Mayfly', rarity: 3, habitat: '川のそば' },
  lacewing: { jp: 'クサカゲロウ', en: 'Lacewing', rarity: 3, habitat: '草むら' },
  hanmyo:   { jp: 'ハンミョウ', en: 'Tiger Beetle', rarity: 4, habitat: '河原' },
  jewelbug: { jp: 'タマムシ', en: 'Jewel Beetle', rarity: 5, habitat: 'エノキ' },
  rhinobeet:{ jp: 'サイカブト', en: 'Rhino Beetle', rarity: 5, habitat: '熱帯' },
  goliath:  { jp: 'ゴライアスオオツノハナムグリ', en: 'Goliath', rarity: 6, habitat: 'アフリカ' },
  titan:    { jp: 'タイタンオオウスバカミキリ', en: 'Titan', rarity: 6, habitat: 'アマゾン' },
};

window.BUG_SHOWCASE = ['kabuto','miyama','herc','ageha','morpho','lady','bee','dragonfly','firefly','mantis','jewelbug','batta','cicada','ant','dango','snail','kok','cricket','spider','worm','moth','fly','inago','mayfly','hanmyo','atlas','okuw','rhinobeet','goliath','actaeon','titan','lacewing'];
